### ISSUE TITLE
version file not correct

### ISSUE THREAD

**Issue by eazzzon** [simonwmatthews/pyMelt#16]
A tiny issue, `pyMelt.__version__ `gives 0.5.1 but not the latest version `1.96`? can be fixed by modification in the `__init__.py` file.

**Comment by simonwmatthews** [comment]
Thanks for spotting this. I have fixed it, as you suggested, and I have pushed the change to the main branch.

**Comment by simonwmatthews** [comment]
(And the updated version will appear on pip the next time I issue a release).
